In [ ]:
# Read Counts

In [95]:
library(dplyr)
library(stringr)
library(tidyr)

In [ ]:
# raw and trimmed reads were written via script - found in 0QC_trimming-all
    # combining and pivoting to make easier to read

In [72]:
setwd('/scratch4/workspace/brooke_sienkiewicz_student_uml_edu-bel_raw/')
reads<-read.csv('reads.csv')
sampleids<-read.table('sampleids.txt', sep = "",header = FALSE)
sampleids$sampleid <- sampleids$V1
sampleids$V1 <- NULL

In [75]:
# make sure raw read counts R1 and R2 match
raw_read_match<-reads %>%
    filter(step == 'raw') %>%
    # add base sampleid to match by
    mutate(sampleid = str_remove(sample, "_R[12]_001.fastq")) %>%
    group_by(sampleid) %>%
    # make sure there are 2 seqs per sameplid and that there is only 1 distinct value (meaning they have the same read count)
    mutate(reads_match = case_when(
      n() == 2 & n_distinct(read_count) == 1 ~ TRUE,
      TRUE ~ FALSE
  )) %>%
  ungroup()

# make sure there are no falses
raw_read_match %>%
    filter(reads_match == FALSE)

# perfect they all match

     sample read_count step sampleid reads_match

In [98]:
# check sample numbers match 
nsample<-nrow(sampleids) # 225 samples
nsample*2

nrow(reads%>%filter(step=='raw'))
# extra sample is "Undetermined"

missing_id <- setdiff(raw_sample, sampleids$sample)
missing_id

[1] 450

[1] 452

[1] "Undetermined"

In [102]:
# filter for just one Read per sample
raw_reads <-raw_read_match %>%
    group_by(sampleid, read_count) %>%
    slice_head(n=1) %>%
    ungroup() %>%
    select(-sample,-reads_match)
nrow(raw_reads)

In [111]:
# separate trimmed step 
trimmed<-reads %>%
    filter(step == 'trimmed') %>%
    # add base ID 
    mutate(sampleid = str_remove(sample, "_R[1]_001")) %>%
    select(-sample)
# and add raw back in 
reads_all<-rbind(raw_reads,trimmed)

In [120]:
# then pivot
reads_wide<-reads_all%>%
    pivot_wider(names_from = step,
                values_from = read_count)
print(reads_wide)

# A tibble: 226 × 3
   sampleid                        raw   trimmed
   <chr>                         <int>     <int>
 1 052022_BEL_CBC_T1_10_PSTR  68572842  68449647
 2 052022_BEL_CBC_T1_11_PSTR  48741905  48660782
 3 052022_BEL_CBC_T1_12_MCAV 166267321 165624856
 4 052022_BEL_CBC_T1_13_MCAV  86263796  86076666
 5 052022_BEL_CBC_T1_1_PAST   85047990  84808864
 6 052022_BEL_CBC_T1_34_PAST  31359387  31274591
 7 052022_BEL_CBC_T1_35_OANN  55101910  55033169
 8 052022_BEL_CBC_T1_39_MCAV  83479374  83235507
 9 052022_BEL_CBC_T1_40_MCAV  68897750  68586963
10 052022_BEL_CBC_T1_41_OANN  40011606  39927902
# ℹ 216 more rows

In [ ]:
# rewrite long and wide format

In [124]:
write.table(reads_all,'reads_filtered.txt', sep = "\t",row.names = FALSE, quote = FALSE)
write.table(reads_wide,'reads_wide.txt', sep = "\t",row.names = FALSE, quote = FALSE)

In [132]:
# percentage lost in trimming step?
reads_wide<-reads_wide %>%
    mutate(pct_yield = round((trimmed / raw) * 100,2))
reads_wide %>% arrange(pct_yield)

    sampleid                       raw       trimmed   pct_yield
1   7_3_Neg                          6030707   5925379 98.25
2   7_11_Neg                        21262507  21046368 98.98
3   052022_BEL_CBC_T2_60_PAST      104718356 103807571 99.13
4   052022_BEL_CBC_T1_52_PAST       94884365  94301477 99.39
5   052022_BEL_CBC_T1_61_PAST       74286118  73869279 99.44
6   062019_BEL_CBC_T2_2_PAST        28081060  27923531 99.44
7   122022_BEL_CBC_T1_150_PAST      33672160  33493920 99.47
8   052022_BEL_CBC_T2_10_MCAV       86868928  86447447 99.51
9   052022_BEL_CBC_T3_40_MCAV       87769648  87360332 99.53
10  122022_BEL_CBC_T1_133_PSTR     103037374 102567043 99.54
11  052022_BEL_CBC_T1_40_MCAV       68897750  68586963 99.55
12  052022_BEL_CBC_T3_49_MCAV       99082077  98632763 99.55
13  122022_BEL_CBC_T2_92_MCAV       32184830  32041701 99.56
14  052022_BEL_CBC_T2_69_OANN      135786053 135204975 99.57
15  052022_BEL_CBC_T3_48_MCAV      121851970 121324489 99.57
16  062019_BEL_CBC_T2_25_PAST       36642549  36483385 99.57
17  122022_BEL_CBC_T2_94_PAST      106608575 106157939 99.58
18  122022_BEL_CBC_T2_95_MCAV       33199587  33061321 99.58
19  122022_BEL_CBC_T2_116_PSTR     152804771 152185903 99.59
20  122022_BEL_CBC_T3_119_MCAV      30642376  30516382 99.59
21  122022_BEL_CBC_T3_129_PAST      84658434  84310638 99.59
22  052022_BEL_CBC_T1_12_MCAV      166267321 165624856 99.61
23  052022_BEL_CBC_T2_56_MCAV       38181744  38034793 99.62
24  062019_BEL_CBC_T2_12_MMEA       34227565  34096607 99.62
25  062019_BEL_CBC_T2_6_MMEA        86632823  86314467 99.63
26  122022_BEL_CBC_T2_88_MCAV       42794470  42634884 99.63
27  122022_BEL_CBC_T3_124_PAST      89357637  89029674 99.63
28  062019_BEL_CBC_T2_13_MMEA      105275129 104892045 99.64
29  062019_BEL_CBC_T3_21_MMEA      102426628 102060375 99.64
30  052022_BEL_CBC_T1_53_PAST       53070363  52883455 99.65
⋮   ⋮                              ⋮         ⋮         ⋮
197 122022_BEL_CBC_T2_87_OFAV       48095561  48025315 99.85
198 122022_BEL_CBC_T2_91_OANN       68640848  68540535 99.85
199 122022_BEL_CBC_T3_149_OANN      42600023  42537140 99.85
200 052022_BEL_CBC_T2_7_PSTR        28113743  28073933 99.86
201 052022_BEL_CBC_T3_65_OFAV       71927615  71828775 99.86
202 062019_BEL_CBC_T2_23_MCAV       96212992  96074505 99.86
203 102019_BEL_CBC_T1_27_PSTR       65177587  65089131 99.86
204 102019_BEL_CBC_T2_36_PSTR       68995431  68897933 99.86
205 102019_BEL_CBC_T3_35_PSTR       73921995  73820685 99.86
206 102019_BEL_CBC_T3_40_PSTR       68667692  68573992 99.86
207 122022_BEL_CBC_T2_107_OANN      65341165  65246444 99.86
208 122022_BEL_CBC_T4_16_OFAV       52163669  52091366 99.86
209 052022_BEL_CBC_T1_4_PSTR        51944878  51875845 99.87
210 052022_BEL_CBC_T2_14_PSTR       74529306  74428797 99.87
211 052022_BEL_CBC_T2_45_PSTR       82391466  82280753 99.87
212 102019_BEL_CBC_T1_25_PSTR       68824320  68736583 99.87
213 102019_BEL_CBC_T2_31_PSTR       46950337  46891332 99.87
214 102019_BEL_CBC_T3_34_PSTR       85430344  85319719 99.87
215 102019_BEL_CBC_T3_37_PSTR       58325293  58246876 99.87
216 122022_BEL_CBC_T2_118_OANN      68969694  68881882 99.87
217 122022_BEL_CBC_T2_97_OFAV       59135469  59059470 99.87
218 122022_BEL_CBC_T3_117_PSTR     166119128 165901176 99.87
219 122022_BEL_CBC_T3_121_OFAV      59033517  58959355 99.87
220 052022_BEL_CBC_T1_35_OANN       55101910  55033169 99.88
221 122022_BEL_CBC_T2_117_PSTR     101829297 101705118 99.88
222 122022_BEL_CBC_T2_93_OFAV       69566198  69479969 99.88
223 122022_BEL_CBC_T4_2_OFAV        66350469  66268433 99.88
224 102019_BEL_CBC_T2_30_PSTR_host  66763853        NA    NA
225 102019_BEL_CBC_T2_31_PSTR_host   5100949        NA    NA
226 Undetermined                   141888465        NA    NA